Add: 卒業試験02実装編
MacOfRinch/mokumoku pull request #2
Opened 2023-05-17 07:13 UTC by MacOfRinch

提供頂いたテストコードをパスできる機能の実装ができましたので、ご確認をよろしくお願い致します。
なお、自動テスト実行上の問題があり`selenium-webdriver`のバージョンを`4.9.0`に変更致しました。

### 選択した事業課題
直近一年間で、2回以上もくもく会に参加してくれた人は利用者全体の1%のみ。もくもく会で気の合う仲間を見つけられなかったのではないか？

### テスト結果
![2023-05-17 16 01のイメージ](https://github.com/MacOfRinch/mokumoku/assets/115129148/ad7a0f4a-b5f6-4f08-a4b4-5fb862c4d76e)

2023-05-18 10:31 UTC, busitora requested changes

2023-05-18 10:31 UTC, busitora commented on app/models/user.rb
> +    Follow.create!(following_id: user_id, follower_id: follower_id)
current_user に対して follow するようにしてください

2023-05-18 10:31 UTC, busitora commented on app/models/user.rb
> +    Follow.find_by(following_id: user_id).destroy
上記同様です また find_by の結果 が nil の場合の考慮をお願いします

2023-05-18 10:31 UTC, busitora commented on spec/factories/follows.rb
> +    follower_id { 1 }
マジックナンバーの記載は避けて下さい！

2023-05-19 04:16 UTC, MacOfRinch commented
bushitora様
レビュー頂きありがとうございます！

ご指摘頂きました内容、承知致しました。
修正ができ次第再提出致しますので、ご確認よろしくお願い申し上げます。

2023-05-19 09:49 UTC, MacOfRinch commented
ご指摘頂きました内容の修正ができましたので、再コミット致しました。
ご確認をよろしくお願い致します。

2023-05-19 10:39 UTC, takyyk commented
@MacOfRinch 
LGTMです！

2023-05-19 12:22 UTC, MacOfRinch commented
takyyk様
ご確認、およびLGTM頂きありがとうございます！

ではこちらはマージさせて頂き、次に進もうと思います。

2023-05-19 12:22 UTC, merged